machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

deployment:
  staging:
    branch: master
    commands:
      - docker login --email=itaydressler@gmail.com --username=itaydressler@gmail.com --password=bdb4a22e0ea0777a2bab2ba19af883ed8c7e9223 registry.heroku.com
      - docker build --rm=false -t registry.heroku.com/my-video-playground/web .
      - docker push registry.heroku.com/my-video-playground/web:latest